export const TOKEN_DECIMALS = 6;
export const TOKEN_TAX = 10;
export const USER_TOKEN_BALANCE = "USER_TOKEN_BALANCE";

export const CONTRACT_BASE_PRICE = "CONTRACT_BASE_PRICE";
export const CONTRACT_STAKED_VALUE = "CONTRACT_STAKED_VALUE";
export const CONTRACT_REDEEM_VALUE = "CONTRACT_REDEEM_VALUE";
export const PROTOCOL_TOTAL_STAKED = "PROTOCOL_TOTAL_STAKED";

export const GET_USER_STAKES = "GET_USER_STAKES";
