"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenSeller__factory = exports.TaxableToken__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var TaxableToken__factory_1 = require("./TaxableToken__factory");
Object.defineProperty(exports, "TaxableToken__factory", { enumerable: true, get: function () { return TaxableToken__factory_1.TaxableToken__factory; } });
var TokenSeller__factory_1 = require("./TokenSeller__factory");
Object.defineProperty(exports, "TokenSeller__factory", { enumerable: true, get: function () { return TokenSeller__factory_1.TokenSeller__factory; } });
